<!-- MAIN PANEL -->
<div id="main" role="main">

	
	<!-- MAIN CONTENT -->
	<div id="content">

		<!-- widget grid -->
		<section id="widget-grid" class="">

			<!-- START ROW -->
			<div class="row">
				
				<!-- NEW COL START -->
				<article class="col-sm-12 col-md-12 col-lg-12">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget" id="wid-id-0" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">

						<header>
							<span class="widget-icon"> <i class="fa fa-edit"></i> </span>
							<h2>Reporte</h2>

						</header>

						<!-- widget div-->
						<div>

							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							<div class="widget-body no-padding">
									
									<form class="smart-form">
									<header>
										Vejez del Inventario
									</header>

								<form class="smart-form">
									<fieldset>
										<div class="row">
											<section class="col col-4">
												<label class="label">Seleccione Inventario</label>
												<label class="select">
													<select id="inventario" >
														<option value="0" selected="" disabled="">Seleccione</option>
														<?php while($reg=$this->inventario->fetch_object()): ?>
															<option value="<?php echo $reg->IDINVENTARIO ?>"><?php echo $reg->NOM_INVENTARIO ?></option>
														<?php endwhile; ?>
													</select> <i></i> </label>
												</section>

												</div>										

											</fieldset>


											<footer>
												<button type="button" id="btn_procesar" class="btn btn-primary"><span class="fa fa-refresh "></span> Procesar</button>
												<a type="button" id="btn_generar_pdf" target="_blank" class="btn btn-info"><span class="fa fa-file-pdf-o"></span> Generar PDF</a>
												<div id="div_mensaje">
													<span style="color: red; font-weight: bold;" id='mensaje'></span>
												</div>						
											</footer>
										</form>

									</div>
									<!-- end widget content -->

								</div>
								<!-- end widget div -->

							</div>
							<!-- end widget -->

						</article>
						<!-- END COL -->

					</div>

					<!-- END ROW -->			


				</section>
				<!-- end widget grid -->

		<!-- widget grid -->
		<section id="widget-grid" class="">

			<!-- row -->
			<div class="row">

				<!-- NEW WIDGET START -->
				<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

					<!-- Widget ID (each widget will need unique ID)-->
					<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
						
						<header>
							<span class="widget-icon"> <i class="fa fa-table"></i> </span>
							<h2>Reporte</h2>

						</header>

						<!-- widget div-->
						<div>

							<!-- widget edit box -->
							<div class="jarviswidget-editbox">
								<!-- This area used as dropdown edit box -->

							</div>
							<!-- end widget edit box -->

							<!-- widget content -->
							<div class="widget-body no-padding">

								<table id="tablaindicador" class="table table-striped table-bordered table-hover" width="100%">
									<thead>	                
										<tr>										
											<th>CATEGORIA</th>
											<th>UND. ACTIVOS</th>
											<th>UND. DAÑADAS</th>
											<th>UND. OBSOLETAS</th>
											<th>UND. VENCIDAS</th>
											<th>TOTAL</th>																	
										</tr>
									</thead>
									<tbody>
									</tbody>
								</table>

							</div>
							<!-- end widget content -->

						</div>
						<!-- end widget div -->

					</div>
					<!-- end widget -->	

					

				</article>
				<!-- WIDGET END -->

			</div>

			<!-- end row -->

			<!-- end row -->

		</section>
		<!-- end widget grid -->

	</div>
	<!-- END MAIN CONTENT -->

</div>
<!-- END MAIN PANEL -->
