<!-- MAIN PANEL -->
<div id="main" role="main">

	<!-- MAIN CONTENT -->
	<div id="content">
		

		<!-- widget content -->
		<div class="widget-body">
			
					<!-- widget grid -->
					<section id="widget-grid" class="">
						<!-- row -->
						<div class="row">				
							<!-- NEW WIDGET START -->
							<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<!-- Widget ID (each widget will need unique ID)-->
								<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

									<header>
										<span class="widget-icon"> <i class="fa fa-table"></i> </span>
										<h2>ACTA DE ENTREGA</h2>
									</header>

									<!-- widget div-->
									<div>
										<!-- widget content -->
										<div class="widget-body no-padding">
											<table id="tablapersonal" class="table table-striped table-bordered table-hover" width="100%">
												<thead>			                
													<tr>
														<th>DNI</th>
														<th>NOMBRE</th>
														<th>AREA/OFICINA</th>
														<th>ESTATUS</th>
														<th>CANTIDAD</th>
														<th>OPCIONES</th>
													</tr>
												</thead>
												<tbody>
												</tbody>
											</table>
										</div>
										<!-- end widget content -->
									</div>
									<!-- end widget div -->
								</div>
								<!-- end widget -->	
							</article>
							<!-- WIDGET END -->		
						</div>
						<!-- end row -->
					</section>
					<!-- end widget grid -->
					

		</div>
		<!-- end widget content -->

	</div>
	<!-- END MAIN CONTENT -->

</div>
<!-- END MAIN PANEL -->
