<!-- MAIN PANEL -->
<div id="main" role="main">

	
	<!-- MAIN CONTENT -->
	<div id="content">
		<!-- widget content -->
		<div class="widget-body">		
			
				<div class="row">
					<!--<div class="col-xs-12 col-sm-9 col-md-7 col-lg-4">-->
					<div class="col-md-6 col-md-offset-3">
						<h1 class="page-title txt-color-blueDark">
							<button data-toggle="modal" href="#addinventario" id="btn_nuevo" type="button" class="btn btn-info btn-sm btn-block"> <i class="fa fa-plus"></i> Nuevo Inventario </button>
						</h1>						
					</div>
				</div>
				<!-- widget grid -->
				<section id="widget-grid" class="">
					<!-- row -->
					<div class="row">				
						<!-- NEW WIDGET START -->
						<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
							<!-- Widget ID (each widget will need unique ID)-->
							<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

								<header>
									<span class="widget-icon"> <i class="fa fa-table"></i> </span>
									<h2>USUARIOS </h2>
								</header>

								<!-- widget div-->
								<div>
									<!-- widget content -->
									<div class="widget-body no-padding">
										<table id="tablainventario" class="table table-striped table-bordered table-hover" width="100%">
											<thead>			                
												<tr>
													<th></i>NOM. INVENTARIO</th>
													<th></i>FECHA INICIO</th>
													<th>FECHA FIN</th>
													<th>ESTADO</th>
													<th>DESCRIPCION</th>
													<th>USUARIO</th>
													<th>OPCIONES</th>
												</tr>
											</thead>
											<tbody>
											</tbody>
										</table>
									</div>
									<!-- end widget content -->
								</div>
								<!-- end widget div -->
							</div>
							<!-- end widget -->	
						</article>
						<!-- WIDGET END -->		
					</div>
					<!-- end row -->
				</section>
				<!-- end widget grid -->
		</div>
		<!-- end widget content -->
	</div>
	<!-- END MAIN CONTENT -->
</div>
<!-- END MAIN PANEL -->


<!-- Modal Inventario -->
<div class="modal fade" id="addinventario" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="title">

				</h4>
			</div>
			<div class="modal-body no-padding">

				<form id="login-form" class="smart-form">

					<fieldset>
						<div style="display: none;"><input type="text" name="idinventario" id="idinventario""></div>
						<section>
							<div class="row">
								<label class="label col col-2">NOMBRE INVENTARIO</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-user"></i>
										<input type="text" class="" name="nombre" id="nombre" maxlength="15">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">FECHAINICIO</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-calendar"></i>
											<input type="text" class="datepicker" name="fechainicio" id="fechainicio" placeholder="Ingrese Fecha inicio">
									</label>
								</div>
							</div>
						</section>	

						<section>
							<div class="row">
								<label class="label col col-2">DESCRIPCION</label>
								<div class="col col-10">
									<label class="textarea"> <i class="icon-append fa fa-comment"></i>								
										<textarea rows="5" id="descripcion" name="descripcion" placeholder="Ingrese Descripcion"></textarea> 
									</label>
								</div>
							</div>
						</section>						


					</fieldset>

					<footer>

						<button type="button" class="btn btn-primary" id="btn_grabar_inventario"> <i class="fa fa-save"> Guardar </i></button>
						<button type="button" class="btn btn-primary" id="btn_actualizar"> <i class="fa fa-save"> Actualizar </i></button>
						<button type="button" class="btn btn-default" data-dismiss="modal">	Cerrar </button>
						<div id="div_mensaje">
							<span style="color: red; font-weight: bold;" id='mensaje'></span>
						</div>
					</footer>
				</form>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div>
<!-- end Modal Inventario -->