<!-- MAIN PANEL -->
<div id="main" role="main">

	

	<!-- MAIN CONTENT -->
	<div id="content">
		

		<!-- widget content -->
		<div class="widget-body">
			
			<ul id="myTab1" class="nav nav-tabs bordered">
				<li class="active">
					<a href="#tab_usuarios" data-toggle="tab"><i class="fa fa-fw fa-lg fa-user"></i>Usuario</a>
				</li>
				<li>
					<a href="#tab_perfiles" data-toggle="tab"><i class="fa fa-fw fa-lg fa-lock"></i>Perfiles</a>
				</li>
			</ul>

			<div id="myTabContent1" class="tab-content padding-10">
				<div class="tab-pane fade in active" id="tab_usuarios">

					<div class="row">
						<!--<div class="col-xs-12 col-sm-9 col-md-7 col-lg-4">-->
						<div class="col-md-6 col-md-offset-3">
							<h1 class="page-title txt-color-blueDark">
								<button data-toggle="modal" href="#addusuario" id="btn_nuevo" type="button" class="btn btn-info btn-sm btn-block"> <i class="fa fa-plus"></i> Nuevo Usuario </button>
							</h1>						
						</div>
					</div>
					<!-- widget grid -->
					<section id="widget-grid" class="">
						<!-- row -->
						<div class="row">				
							<!-- NEW WIDGET START -->
							<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<!-- Widget ID (each widget will need unique ID)-->
								<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

									<header>
										<span class="widget-icon"> <i class="fa fa-table"></i> </span>
										<h2>USUARIOS </h2>
									</header>

									<!-- widget div-->
									<div>
										<!-- widget content -->
										<div class="widget-body no-padding">
											<table id="tablausuarios" class="table table-striped table-bordered table-hover" width="100%">
												<thead>			                
													<tr>
														<th>USUARIO</th>
														<th>NOMBRE</th>
														<th>AREA</th>
														<th>ESTADO</th>
														<th>OPCIONES</th>
													</tr>
												</thead>
												<tbody>
												</tbody>
											</table>
										</div>
										<!-- end widget content -->
									</div>
									<!-- end widget div -->
								</div>
								<!-- end widget -->	
							</article>
							<!-- WIDGET END -->		
						</div>
						<!-- end row -->
					</section>
					<!-- end widget grid -->
				</div>

				<div class="tab-pane fade" id="tab_perfiles">
					<div class="row">
						<!--<div class="col-xs-12 col-sm-9 col-md-7 col-lg-4">-->
						<div class="col-md-6 col-md-offset-3">
							<h1 class="page-title txt-color-blueDark">
								<button data-toggle="modal" href="#addperfil" id="btn_nuevo_perfil" type="button" class="btn btn-info btn-sm btn-block"> <i class="fa fa-plus"></i> Nuevo Perfil </button>
							</h1>						
						</div>
					</div>
					<!-- widget grid -->
					<section id="widget-grid" class="">
						<!-- row -->
						<div class="row">				
							<!-- NEW WIDGET START -->
							<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
								<!-- Widget ID (each widget will need unique ID)-->
								<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">

									<header>
										<span class="widget-icon"> <i class="fa fa-table"></i> </span>
										<h2>PERFILES</h2>
									</header>

									<!-- widget div-->
									<div>
										<!-- widget content -->
										<div class="widget-body no-padding">
											<table id="tablaperfiles" class="table table-striped table-bordered table-hover" width="100%">
												<thead>			                
													<tr>
														<th>PERFIL</th>
														<th>CANT. MODULOS</th>
														<th>IDUSUARIOCREACION</th>
														<th>OPCIONES</th>
													</tr>
												</thead>
												<tbody>
												</tbody>
											</table>
										</div>
										<!-- end widget content -->
									</div>
									<!-- end widget div -->

								</div>
								<!-- end widget -->	
							</article>
							<!-- WIDGET END -->		
						</div>
						<!-- end row -->
					</section>
					<!-- end widget grid -->
				</div>

			</div>

		</div>
		<!-- end widget content -->

	</div>
	<!-- END MAIN CONTENT -->

</div>
<!-- END MAIN PANEL -->


<!-- Modal Usuario -->
<div class="modal fade" id="addusuario" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="title">

				</h4>
			</div>
			<div class="modal-body no-padding">

				<form id="login-form" class="smart-form">

					<fieldset>
						<section>
							<div class="row">
								<label class="label col col-2">USUARIO</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-user"></i>
										<input type="text" class="letras" name="usuario" id="usuario">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">APELLIDO PATERNO</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-user"></i>
										<input type="text" class="letras" name="apellido_pat" id="apellido_pat">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">APELLIDO MATERNO</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-user"></i>
										<input type="text" class="letras" name="apellido_mat" id="apellido_mat">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">NOMBRE</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-user"></i>
										<input type="text" class="letras" name="nombre" id="nombre">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">DNI</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-user"></i>
										<input type="text" class="numeros" name="dni" id="dni" maxlength="8">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">EMAIL</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-google-plus"></i>
										<input type="email"  name="email" id="email">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">TELEFONO</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-phone"></i>
										<input type="text" class="numeros" name="telefono" id="telefono">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">OFICINA</label>
								<div class="col col-10">											
									<select style="width:100%" class="form-control" id="oficina" name="oficina">
										<option value="" selected="selected">SELECCIONE</option>
										<?php while($reg=$this->oficina->fetch_object()):?>
											<option value="<?php echo $reg->IDOFICINA; ?>" > <?php echo $reg->NOMBRE ?></option>
										<?php endwhile; ?>
									</select>

								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">CONTRASEÑA</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-lock"></i>
										<input type="password" name="password" id="password">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">REPETIR CONTRASEÑA</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-lock"></i>
										<input type="password" name="password2" id="password2">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">ESTADO</label>
								<div class="col col-10">
									<select name="status" id="status" style="width: 100%" class="form-control">
										<option value="1" selected="selected">ACTIVO</option>
										<option value="0" >INACTIVO</option>
									</select>
								</div>
							</div>
						</section>


					</fieldset>

					<footer>

						<button type="button" class="btn btn-primary" id="btn_grabar_usuario"> <i class="fa fa-save"> Guardar </i></button>
						<button type="button"  data-toggle="modal" href="#addpermisos" class="btn btn-info" id="btn_acceso"> <i class="fa fa-unlock"> Añadir Permisos </i></button>
						<button type="button" class="btn btn-primary" id="btn_actualizar"> <i class="fa fa-save"> Actualizar </i></button>
						<button type="button" class="btn btn-default" data-dismiss="modal">	Cerrar </button>
						<div id="div_mensaje">
							<span style="color: red; font-weight: bold;" id='mensaje'></span>
						</div>
					</footer>
				</form>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Modal Perfiles -->
<div class="modal fade" id="addperfil" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="title_profile">

				</h4>
			</div>
			<div class="modal-body no-padding">

				<form id="form_perfiles" class="smart-form">

					<fieldset>
						<input style="display: none;" type="text" id="getidperfil" name="getidperfil">
						<section>
							<div class="row">
								<label class="label col col-2">NOMBRE PERFIL</label>
								<div class="col col-10">
									<label class="input"> <i class="icon-append fa fa-user"></i>
										<input type="text" class="letras" name="perfil" id="perfil">
									</label>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">SELECCIONE MODULO</label>
								<div class="col col-10">
									<select  multiple="multiple" class="form-control" id="idmodulo" name="idmodulo[]" style="width: 100%">
										
									</select>
								</div>
							</div>
						</section>

					</fieldset>

					<footer>

						<button type="button" class="btn btn-primary" id="btn_grabar_perfil"> <i class="fa fa-save"> Guardar </i></button>
						<button type="button" class="btn btn-primary" id="btn_update_perfil"> <i class="fa fa-save"> Actualizar </i></button>
						<button type="button" class="btn btn-default" data-dismiss="modal">	Cerrar </button>
						<div id="div_mensaje_profile">
							<span style="color: red; font-weight: bold;" id='mensaje_profile'></span>
						</div>
					</footer>
				</form>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Modal Permisos -->
<div class="modal fade" id="addpermisos" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-md">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="title">Control de Accesos</h4>
			</div>
			<div class="modal-body no-padding">
				<form id="form_perfiles" class="smart-form">
					<fieldset>
						<section>
							<div class="row">
								<label class="label col col-2">Seleccione Perfil</label>
								<div class="col col-10">
									<select  class="form-control" id="idperfil" name="idperfil" style="width: 100%">
									</select>
								</div>
							</div>
						</section>

						<section>
							<div class="row">
								<label class="label col col-2">Seleccione Permisos</label>
								<div class="col col-10">
									<div class="inline-group">
										<label class="checkbox">
										<input type="checkbox" name="check_lectura" id="check_lectura">
										<i></i>Lectura</label>
										<label class="checkbox">
										<input type="checkbox" name="check_escritura" id="check_escritura">
										<i></i>Escritura</label>													
									</div>
								</div>
							</div>
						</section>

					</fieldset>
					<footer>
						<button type="button" class="btn btn-primary" id="btn_grabar_permisos"> <i class="fa fa-save"> Guardar </i></button>
						<button type="button" class="btn btn-default" data-dismiss="modal">	Cerrar </button>
						<div id="div_mensaje_permiso">
							<span style="color: red; font-weight: bold;" id='mensaje_permiso'></span>
						</div>
					</footer>
				</form>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
